version: '3.8'

services:
    lottery_db:
        image: postgres
        environment:
            POSTGRES_DB: lottery_db
            POSTGRES_USER: test_user
            POSTGRES_PASSWORD: test_password
        ports:
            - '5555:5432'