spring:
  datasource:
    url: jdbc:postgresql://${LOTTERY_DB_HOST}/${LOTTERY_DB_NAME}
    username: ${LOTTERY_DB_USERNAME}
    password: ${LOTTERY_DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        show_sql: false

  liquibase:
    change-log: classpath:/db/changelog/master-changelog.yml
